// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-east-2:8a526480-a449-4262-8807-3c87a79391b1',
    'aws_cognito_region': 'us-east-2',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'test-hosting-mobilehub-516087303',
    'aws_content_delivery_bucket_region': 'us-east-2',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd3en7kl1qxzca1.cloudfront.net',
    'aws_mobile_analytics_app_id': '747ccfadda3a483c951ea70bc0309868',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '92da0989-5c10-4a71-9a5c-56c608b19485',
    'aws_project_name': 'Test',
    'aws_project_region': 'us-east-2',
    'aws_resource_name_prefix': 'test-mobilehub-516087303',
}

export default awsmobile;
